### PR TITLE
Add Portis

### PR DESCRIPTION
**Pull request by jessgusclark**
For testing, all the functions worked except setting a subdomain with a different owner. See below for full test results.

This is in Draft until the rLogin PR is merged & deployed: https://github.com/rsksmart/rLogin/pull/89 . It was tested locally with `yarn link`

### CODE REVIEW

**Comment by jessgusclark** [comment]
# RNS Manager Integration Checklist

- [x] Search and Resolve
- [ ] Register
- [ ] Register refresh page (localstorage)
- [ ] Resolve

---
## Admin

- DomainInfo Screen
    - [ ] Set Controller
    - [ ] Reclaim
    - [ ] Transfer

- Your Addresses
    - [ ] Set New Address
    - [ ] Edit existing Address
    - [ ] Delete Address


- Subdomains
    - [ ] Create Subdomain
        - [ ] Create Subdomain with owner self
        - [ ] Create subdomain with owner different
    - [ ] Edit Subdomain
    - [ ] Delete Subdomain
- My URL
    - [ ] Set Content Hash
    - [ ] Edit Content Hash
- Resolver 
    - [ ] Set Resolver
    - [ ] Set Contract ABI
    - [ ] Set Content Hash
    - [ ] Migrate Resolver without addresses
    - [ ] Migrate Resolver with Addresses
- Reverse
    - [ ] Set Reverse

---
*[Checklist template](https://hackmd.io/HAausHK7SNGNIXVlFqGxtA?view)*

**Comment by jessgusclark** [comment]
Wait to merge until the next version of rlogin, (prod or beta) is released. See this PR: https://github.com/rsksmart/rif-identity-manager/pull/81

**Review by ilanolkies — CHANGES_REQUESTED** [review]
Let's use `v1.0.8`

**Comment by jessgusclark** [comment]
Rebased and bumped rLogin version to v1.0.8. Ready to be merged.

**Review by ilanolkies — APPROVED** [review]

**Pull request merged**
