### PR TITLE
Update RIF logo

### PR DESCRIPTION
**Pull request by jessgusclark**
Updates the logo on the header, footer, and favicon.

- Removed the testnet version of the logo since the indicator light has the network name on it. Also, the text "testnet" was blurry when converted to vector. 

This is what the header looks like:

image

I'm unsure of the style guidelines, but this may look better with white. Here is what that would look like:
image

Or, better a mix of black and white;

image

### CODE REVIEW

**Review by ilanolkies — COMMENTED** [review]
What do you think @miltonwg ?

**Comment by jessgusclark** [comment]
Forced pushes are the result of rebasing.

**Comment by miltonwg** [comment]
I like the full white one. But first I'll check with Marketing so we don't have to change it again afterwards.

**Comment by miltonwg** [comment]
@jessgusclark let's go for full white!

**Review by ilanolkies — APPROVED** [review]

**Pull request merged**
